apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperauth
  namespace: hyperauth
  labels:
    app: hyperauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperauth
  template:
    metadata:
      labels:
        app: hyperauth
    spec:
      volumes:
      - name: ssl
        secret:
          secretName: hyperauth-https-secret
      containers:
      - name: hyperauth
        image: tmaxcloudck/hyperauth:b1.0.10.0
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_VENDOR     # postgres / tibero
          value: "postgres"     
        - name: DB_PORT       # postgres : 31226, tibero : 32571
          value: "31226"     
        - name: DB_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DB_USER
          value: "keycloak"
        - name: DB_PASSWORD
          value: "keycloak" 
        - name: KEYCLOAK_WELCOME_THEME
          value: tmax
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        volumeMounts:
        - name: ssl
          mountPath: /etc/x509/https
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
